chore(vuln-scanner): allow supplying filesystem path
We now allow using `path` arg and not only `image` such that users can scan
directories too

diff --git a/vulnerabilities-scanner/action.yml b/vulnerabilities-scanner/action.yml
--- a/vulnerabilities-scanner/action.yml
+++ b/vulnerabilities-scanner/action.yml
@@ -4,17 +4,40 @@ description: "Scan container images for vulnerabilities using Grype"
 inputs:
   image:
     description: "The container image to scan, use complete image reference (e.g., 'nginx:latest' or 'myregistry.com/myimage:tag')"
-    required: true
+    required: false
+  path:
+    description: "Path to the file system to scan (e.g., a directory containing extracted image layers)"
+    required: false
 
 runs:
   # Composite implies that the below steps will be run in the same runner as the calling workflow and not in a separate container
   using: composite
   steps:
-    - uses: anchore/scan-action@8d2fce09422cd6037e577f4130e9b925e9a37175
+    - name: Validate Inputs
+      if: ${{ inputs.image == '' && inputs.path == '' || (inputs.image != '' && inputs.path != '') || (inputs.image == '' && inputs.path == '') }}
+      shell: bash
+      run: |
+        echo "Error: You must provide either 'image' or 'path' input."
+        exit 1
+    - if: ${{ inputs.image != '' && inputs.path == '' }}
+      uses: anchore/scan-action@8d2fce09422cd6037e577f4130e9b925e9a37175
+      name: Scan for Vulnerabilities
       id: scan
       continue-on-error: true
       with:
         image: ${{ inputs.image }}
+        output-format: "json"
+        fail-build: true
+        severity-cutoff: "high"
+        only-fixed: true
+
+    - if: ${{ inputs.path != '' && inputs.image == '' }}
+      uses: anchore/scan-action@8d2fce09422cd6037e577f4130e9b925e9a37175
+      name: Scan for Vulnerabilities
+      id: scan
+      continue-on-error: true
+      with:
+        path: ${{ inputs.path }}
         output-format: "json"
         fail-build: true
         severity-cutoff: "high"
